[package]
name = "cached-pair"
version = "0.4.0"
edition = "2021"
license-file = "LICENSE"
description = "A simple pair of values, where the one can be convertible to the other."

[dependencies]
itertools = "0.14.0"

[features]
default = []
