[package]
name = "cached-pair"
version = "0.8.0"
edition = "2021"
license-file = "LICENSE"
description = "A simple pair of values, where the one can be convertible to the other."
documentation = "https://docs.rs/cached-pair/latest/cached_pair/"

[dependencies]
derive_more = { version = "1.0.0", features = ["debug"] }
itertools = "0.14.0"

[features]
default = []
